---
# Source: logrotate/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    configmap.reloader.stakater.com/reload: logrotate
  name: logrotate
  namespace: kube-system
spec:
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: logrotate
      group: com.stakater.platform
      provider: stakater
      version: "3.13.0"
      chart: "logrotate-1.0.19"
      release: "logrotate"
      heritage: "Helm"
  template:
    metadata:
      labels:
        app: logrotate
        group: com.stakater.platform
        provider: stakater
        version: "3.13.0"
        chart: "logrotate-1.0.19"
        release: "logrotate"
        heritage: "Helm"
      name: logrotate
      namespace: kube-system
    spec:
      containers:
      - name: logrotate
        image: "stakater/logrotate:3.13.0"
        securityContext:
          privileged: true
        volumeMounts:
         - name: containers
           mountPath: /var/lib/docker/containers
         - name: logrotate-config
           mountPath: /etc/logrotate.d/k8s-rotator.conf
           subPath: k8s-rotator.conf
        env:
          - name: CRON_SCHEDULE
            value: "0 1 * * *"
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      volumes:
         - hostPath:
             path: /var/lib/docker/containers
           name: containers
         - configMap:
            name: logrotate
           name: logrotate-config
---
# Source: logrotate/templates/configMap.yaml
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    annotations:
      fabric8.io/target-platform: kubernetes
    labels:
      app: logrotate
      group: com.stakater.platform
      provider: stakater
      version: "3.13.0"
      chart: "logrotate-1.0.19"
      release: "logrotate"
      heritage: "Helm"
    name: logrotate
    namespace: kube-system
  data:
    k8s-rotator.conf:  |-
      /var/lib/docker/containers/*/*.log {
        weekly
        rotate 1
        copytruncate
        missingok
        notifempty
        compress
        maxsize 10M
      }
